# Table of Contents
 <p><div class="lev1"><a href="#Task-1.-Compiling-Ebola-Data"><span class="toc-item-num">Task 1.&nbsp;&nbsp;</span>Compiling Ebola Data</a></div>
 <div class="lev1"><a href="#Task-2.-RNA-Sequences"><span class="toc-item-num">Task 2.&nbsp;&nbsp;</span>RNA Sequences</a></div>
 <div class="lev1"><a href="#Task-3.-Class-War-in-Titanic"><span class="toc-item-num">Task 3.&nbsp;&nbsp;</span>Class War in Titanic</a></div></p>

In [1]:
import pandas as pd
import numpy as np
import os
pd.options.mode.chained_assignment = None  # default='warn', Mutes warnings when copying a slice from a DataFrame.

DATA_FOLDER = './Data/'

## Task 1. Compiling Ebola Data

The `DATA_FOLDER/ebola` folder contains summarized reports of Ebola cases from three countries (Guinea, Liberia and Sierra Leone) during the recent outbreak of the disease in West Africa. For each country, there are daily reports that contain various information about the outbreak in several cities in each country.

Use pandas to import these data files into a single `Dataframe`.
Using this `DataFrame`, calculate for *each country*, the *daily average* per year of *new cases* and *deaths*.
Make sure you handle all the different expressions for *new cases* and *deaths* that are used in the reports.

In [112]:
#Initialization
#The dataFrame we gonna fill and work with.
df = pd.DataFrame()
EBOLA_FOLDER = DATA_FOLDER + "Ebola/"
COLUMNS_TO_KEEP = pd.DataFrame([{'guinea': ['Date', 'Description' , 'Totals'],
                    'liberia':['Date', 'Variable', 'National'],
                    'sl':['date', 'variable', 'National']}])

GOOD_HEADER = ['Date', 'Description' , 'Totals']

In [113]:

#For all the directory in Ebola directory load the .csv file in it.
for dir in os.listdir(EBOLA_FOLDER):
    if "_data" in dir:
        #Substract _data to only get the country name
        country = dir[:-5]
        #For each file in the country directory
        for file in os.listdir(EBOLA_FOLDER + dir):
            if file.endswith(".csv"):
                tmp = pd.read_csv(EBOLA_FOLDER + dir + '/' + file, usecols= COLUMNS_TO_KEEP[country].at[0])
                tmp.columns = GOOD_HEADER
                nbRow = tmp.shape[0]
                charlist = [country]*nbRow
                chararray = np.array(charlist)
                #Add a column in the 1st position representing the country.
                tmp.insert(0, 'Country', chararray)
                if(df.empty):
                    df = tmp
                else:
                    df = df.merge(tmp,how='outer')


#Mean of new cases per month & country yearly.


df
#df.to_csv('df.csv')

,Country,Date,Description,Totals
0,guinea,2014-08-04,New cases of suspects,5
1,guinea,2014-08-04,New cases of probables,0
2,guinea,2014-08-04,New cases of confirmed,4
3,guinea,2014-08-04,Total new cases registered so far,9
4,guinea,2014-08-04,Total cases of suspects,11
5,guinea,2014-08-04,Total cases of probables,133
6,guinea,2014-08-04,Total cases of confirmed,351
7,guinea,2014-08-04,Cumulative (confirmed + probable + suspects),495
8,guinea,2014-08-04,New deaths registered today,2
9,guinea,2014-08-04,New deaths registered today (confirmed),2
10,guinea,2014-08-04,New deaths registered today (probables),0
11,guinea,2014-08-04,New deaths registered today (suspects),0
12,guinea,2014-08-04,Total deaths of suspects,2
13,guinea,2014-08-04,Total deaths of probables,133
14,guinea,2014-08-04,Total deaths of confirmed,228
15,guinea,2014-08-04,Total deaths (confirmed + probables + suspects),363
16,guinea,2014-08-04,Total PEC center today,31
17,guinea,2014-08-04,Total PEC center today (confirmed),18
18,guinea,2014-08-04,Total PEC center today (probables),0
19,guinea,2014-08-04,Total PEC center today (suspects),13
20,guinea,2014-08-04,Total of deaths in confirmed cases in CTE,138
21,guinea,2014-08-04,Total of cured in confirmed cases in CTE,89
22,guinea,2014-08-04,Number of male confirmed cases,161
23,guinea,2014-08-04,Number of female confirmed cases,190
24,guinea,2014-08-04,Number of male probables cases,52
25,guinea,2014-08-04,Number of female probables cases,81
26,guinea,2014-08-04,Number of male suspects cases,7
27,guinea,2014-08-04,Number of female suspects cases,6
28,guinea,2014-08-04,Total number of male cases,220
29,guinea,2014-08-04,Total number of female cases,277
...,...,...,...,...
7098,sl,2014-12-13,cum_probable,79
7099,sl,2014-12-13,cum_confirmed,6638
7100,sl,2014-12-13,death_suspected,NaN
7101,sl,2014-12-13,death_probable,NaN
7102,sl,2014-12-13,death_confirmed,NaN
7103,sl,2014-12-13,cfr,NaN
7104,sl,2014-12-13,etc_new_admission,NaN
7105,sl,2014-12-13,etc_currently_admitted,NaN
7106,sl,2014-12-13,etc_cum_admission,NaN
7107,sl,2014-12-13,etc_new_deaths,NaN
7108,sl,2014-12-13,etc_cum_deaths,NaN
7109,sl,2014-12-13,etc_new_discharges,NaN
7110,sl,2014-12-13,etc_cum_discharges,NaN
7111,sl,2014-12-13,cum_contacts,NaN
7112,sl,2014-12-13,cum_completed_contacts,NaN
7113,sl,2014-12-13,contacts_followed,NaN
7114,sl,2014-12-13,new_contacts,NaN
7115,sl,2014-12-13,contacts_healthy,NaN
7116,sl,2014-12-13,contacts_ill,NaN
7117,sl,2014-12-13,contacts_not_seen,NaN
7118,sl,2014-12-13,new_completed_contacts,NaN
7119,sl,2014-12-13,percent_seen,NaN
7120,sl,2014-12-13,total_lab_samples,NaN
7121,sl,2014-12-13,repeat_samples,NaN
7122,sl,2014-12-13,new_samples,NaN
7123,sl,2014-12-13,new_positive,NaN
7124,sl,2014-12-13,new_negative,NaN
7125,sl,2014-12-13,pending,NaN
7126,sl,2014-12-13,positive_corpse,NaN
7127,sl,2014-12-13,negative_corpse,NaN

## Task 2. RNA Sequences

In the `DATA_FOLDER/microbiome` subdirectory, there are 9 spreadsheets of microbiome data that was acquired from high-throughput RNA sequencing procedures, along with a 10<sup>th</sup> file that describes the content of each. 

Use pandas to import the first 9 spreadsheets into a single `DataFrame`.
Then, add the metadata information from the 10<sup>th</sup> spreadsheet as columns in the combined `DataFrame`.
Make sure that the final `DataFrame` has a unique index and all the `NaN` values have been replaced by the tag `unknown`.

In [ ]:
# Write your answer here

## Task 3. Class War in Titanic

Use pandas to import the data file `Data/titanic.xls`. It contains data on all the passengers that travelled on the Titanic.

In [ ]:
from IPython.core.display import HTML
HTML(filename=DATA_FOLDER+'/titanic.html')

For each of the following questions state clearly your assumptions and discuss your findings:
1. Describe the *type* and the *value range* of each attribute. Indicate and transform the attributes that can be `Categorical`. 
2. Plot histograms for the *travel class*, *embarkation port*, *sex* and *age* attributes. For the latter one, use *discrete decade intervals*. 
3. Calculate the proportion of passengers by *cabin floor*. Present your results in a *pie chart*.
4. For each *travel class*, calculate the proportion of the passengers that survived. Present your results in *pie charts*.
5. Calculate the proportion of the passengers that survived by *travel class* and *sex*. Present your results in *a single histogram*.
6. Create 2 equally populated *age categories* and calculate survival proportions by *age category*, *travel class* and *sex*. Present your results in a `DataFrame` with unique index.

In [ ]:
# Write your answer here